# print

print('Hellow word') # print com texto (string) dentro, exibe o que esta dentro do parentezes

print('Fabrica' + 'de progamadores') # print com dois elementos somados "+"
print('vamos','aprender') # print com dois elementos,exibe os dois textos juntos

var = 'hellow word!' + 'python é legal'
print(var) # print com variavel, exibe o valor salvo na variavel

nome = 'gabriel'
print('Olá',nome) # print com dois elementos, uma string e uma variavel

n1 =2
n2 =7
n3 =8
print((n1+n2+n3)/3) # exibe o resultado da expressão matemática



print('1' == 1)